import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { REPO_ROOT } from '../src/config.js';
import { closePdf, loadPdf } from '../src/pdf/load.js';
import { extractPage } from '../src/pdf/extract-page.js';
import type { ExtractedPage } from '../src/pdf/types.js';

/** Absolute path of a file generated by `npm run fixtures`. */
export const fixturePath = (name: string): string => path.join(REPO_ROOT, 'fixtures', name);

export async function readFixture(name: string): Promise<Buffer> {
  return readFile(fixturePath(name));
}

/** Extracts every page of a fixture with the real pdf.js (in this process, no worker). */
export async function extractFixture(name: string): Promise<ExtractedPage[]> {
  const doc = await loadPdf(new Uint8Array(await readFixture(name)));
  try {
    const pages: ExtractedPage[] = [];
    for (let n = 1; n <= doc.numPages; n += 1) pages.push(await extractPage(doc, n));
    return pages;
  } finally {
    await closePdf(doc);
  }
}

/** All whitespace (including the line breaks pdf wrapping put in) as single spaces: for comparing sentences. */
export const flat = (text: string): string => text.replace(/\s+/gu, ' ').trim();

export const headingsOf = (page: ExtractedPage): string[] =>
  page.blocks.filter((block) => block.isHeading).map((block) => flat(block.text));
