/*
 * GENERATED by `npm run calibrate` (test/evals/rag-calibration.eval.test.ts + rag/calibration.ts) (measured on 2026-10-02, recomputed offline on 2026-10-03).
 * Do not edit by hand: run the calibration again after changing the embedding model, its prefixes, the chunk sizes or the
 * documents it learns from. The data of the run is in .data/task4/calibration.json.
 *
 * gemini-embedding-2, 768 dimensions, 29 answerable, 53 unrelated and 6 trap questions:
 *   same language: highest unrelated question 0.58 (floor -0.01 above it), lowest answerable 0.61 (floor 0.04 below it), 25 unrelated and 10 answerable questions reach the cosine test; 2 unrelated one(s) leak past the floor to guards 2 and 3, 0 answerable one(s) are stopped
 *   across languages: highest unrelated question 0.57 (floor 0.03 above it), lowest answerable 0.69 (floor 0.09 below it), 25 unrelated and 10 answerable questions reach the cosine test; 0 unrelated one(s) leak past the floor to guards 2 and 3, 0 answerable one(s) are stopped
 *   checks: ok (no answerable question stopped, every floor at least 0.03 below the lowest answerable one)
 *   left out one question (document) at a time, the floors would stop 1 (1) answerable question(s)
 *   shared words: generic ones cover up to 0.42 of a question that is not about the document, answerable questions
 *   with generic words cover down to 0.07: a shared word is evidence from a coverage of 0.45, the lowest that stops
 *   48 unrelated question(s) at the floors while stopping 0 answerable one(s)
 *   past the gate without the cosine test (a shared word counts as evidence): 0 unrelated question(s) (0 on a name, 0 on an identifier, 0 on shared words) and 0 trap question(s); they are not in the leak counts above
 *   strong marks: the highest trap question is 0.69 in the same language and 0.67 across languages (each mark is the lowest that keeps every trap weak)
 *   note: same language: the highest unrelated question (0.58) is within 0.03 of the lowest answerable one (0.61): the floor stays clear of the answerable one, and unrelated questions leak to guards 2 and 3
 */
import type { EvidenceThresholds } from './constants.js';

export const CALIBRATED_THRESHOLDS: Readonly<Record<string, EvidenceThresholds>> = {
  'gemini-embedding-2': {
    floor: 0.6,
    sameLanguageFloor: 0.57,
    strong: 0.71,
    crossLanguageStrong: 0.69,
    informativeCoverage: 0.45,
  },
};
